GET https://captcha-iamrz1.cloud.okteto.net/api/v1/get-captcha
Accept: application/json

###
POST http://localhost:8080/api/v1/public/customers/signup
Content-Type: application/json

{
  "captcha_id": "4uBAfHvVUEs9fkhFmGVA",
  "captcha_value": "11111",
  "full_name": "Rezoan",
  "password": "Abcd2021!",
  "username": "01746410748"
}

###

POST http://localhost:8080/api/v1/public/customers/verify-signup
Content-Type: application/json

{
  "otp": "30358",
  "username": "01746410748"
}

###
POST http://localhost:8080/api/v1/public/customers/login
Content-Type: application/json

{
  "password": "Abcd2021!",
  "username": "01746410748"
}

###
PATCH http://localhost:8080/api/v1/private/customers/profile
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjAxNzQ2NDEwNzQ4Iiwicm9sZSI6IiIsInVzZXJfdHlwZSI6ImN1c3RvbWVyIiwiZXhwIjoxNjI2NjQwMTY3LCJpYXQiOjE2MjY2MzgzNjd9.DjPXbUMe-l47TuEC9qC3SO1Bd0SJvWc_4Ptgd7VKwfE

{
  "birth_date": "2006-01-02T15:04:05.000Z",
  "email": "me@you.com",
  "full_name": "Rezoan Tamal",
  "gender": "male",
  "occupation": "n/a",
  "organization": "n/a"
}

###

GET http://localhost:8080/api/v1/private/customers/profile
Accept: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjAxNzQ2NDEwNzQ3Iiwicm9sZSI6IiIsInVzZXJfdHlwZSI6ImN1c3RvbWVyIiwiZXhwIjoxNjI2NjM1Nzk5LCJpYXQiOjE2MjY2MzM5OTl9.mxxc7X6F_dwgF12NnyoCJt5fH1foITF5VG85cJlhp8o

###

GET http://localhost:8080/api/v1/private/customers/verify-token
Accept: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjAxNzQ2NDEwNzQ4Iiwicm9sZSI6IiIsInVzZXJfdHlwZSI6ImN1c3RvbWVyIiwiZXhwIjoxNjI2Njk3NjY0LCJpYXQiOjE2MjY2OTU4NjR9.LKBj-_GWTadDKvsEtg9GtUNXQZtk01Jr88ct900O-P8

###

GET http://localhost:8080/api/v1/private/customers/refresh-token
Accept: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjAxNzQ2NDEwNzQ2Iiwicm9sZSI6IiIsInVzZXJfdHlwZSI6IiIsImV4cCI6MTYyNjk1NDI0OSwiaWF0IjoxNjI2MzQ5NDQ5fQ.Bvbvk6fIULgpq43lDMNkRhzZwz6EA3rpiJy-M--zxKY


###
POST http://localhost:8080/api/v1/public/customers/forgot-password
Content-Type: application/json

{
  "captcha_id": "4uBAfHvVUEs9fkhFmGVA",
  "captcha_value": "11111",
  "username": "01746410748"
}

###
POST http://localhost:8080/api/v1/public/customers/set-password
Content-Type: application/json

{
  "username": "01746410748",
  "password": "Abc2021!",
  "otp": "94298"
}

###

PATCH http://localhost:8080/api/v1/private/customers/password
Content-Type: application/json
Accept: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjAxNzQ2NDEwNzQ4Iiwicm9sZSI6IiIsInVzZXJfdHlwZSI6ImN1c3RvbWVyIiwiZXhwIjoxNjI2Njk3NjY0LCJpYXQiOjE2MjY2OTU4NjR9.LKBj-_GWTadDKvsEtg9GtUNXQZtk01Jr88ct900O-P8

{
  "current_password": "Abc2021!",
  "new_password": "Abcd2021!"
}
