basePath: /
definitions:
  model.CustomerSignupReq:
    properties:
      captcha_id:
        type: string
      captcha_value:
        type: string
      full_name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  model.CustomerSignupVerificationReq:
    properties:
      otp:
        type: string
      username:
        type: string
    type: object
  model.EmptyObject:
    type: object
  response.CustomerErrData:
    properties:
      object:
        $ref: '#/definitions/model.EmptyObject'
    type: object
  response.CustomerErrorRes:
    properties:
      data:
        $ref: '#/definitions/response.CustomerErrData'
      message:
        example: failure message
        type: string
      success:
        example: false
        type: boolean
    type: object
  response.EmptySuccessData:
    properties:
      object:
        $ref: '#/definitions/model.EmptyObject'
    type: object
  response.EmptySuccessRes:
    properties:
      data:
        $ref: '#/definitions/response.EmptySuccessData'
      message:
        example: success message
        type: string
      success:
        example: false
        type: boolean
    type: object
host: https://auth-iamrz1.cloud.okteto.net
info:
  contact:
    email: my.full.name.in.lower.case@gmail.com
    name: Rezoan Tamal
  description: This is auth REST api server
  termsOfService: tbd
  title: auth
  version: "1.0"
paths:
  /api/v1/public/customers/signup:
    post:
      consumes:
      - application/json
      description: Signup a new customer for a valid non-existing phone number
      parameters:
      - description: All fields are mandatory
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/model.CustomerSignupReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.EmptySuccessRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.CustomerErrorRes'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.CustomerErrorRes'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.CustomerErrorRes'
      summary: Signup a new customer
      tags:
      - Customers
  /api/v1/public/customers/verify-signup:
    post:
      consumes:
      - application/json
      description: VerifySignUp uses user defined otp and matches it with existing
        reference in cache to verify a signup
      parameters:
      - description: All fields are mandatory
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/model.CustomerSignupVerificationReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.EmptySuccessRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.CustomerErrorRes'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.CustomerErrorRes'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.CustomerErrorRes'
      summary: Verify a new customer using otp
      tags:
      - Customers
swagger: "2.0"
