basePath: /
definitions:
  model.Customer:
    properties:
      birth_date:
        type: string
      created_at:
        type: string
      full_name:
        type: string
      gender:
        type: string
      is_deleted:
        type: boolean
      is_verified:
        type: boolean
      recovery_phone_number:
        type: string
      status:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  model.CustomerSignupReq:
    properties:
      captcha_id:
        type: string
      captcha_value:
        type: string
      full_name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  model.EmptyObject:
    type: object
  response.CustomerData:
    properties:
      object:
        $ref: '#/definitions/model.Customer'
    type: object
  response.CustomerErrData:
    properties:
      object:
        $ref: '#/definitions/model.EmptyObject'
    type: object
  response.CustomerErrorRes:
    properties:
      data:
        $ref: '#/definitions/response.CustomerErrData'
      message:
        example: failure message
        type: string
      success:
        example: false
        type: boolean
    type: object
  response.CustomerSuccessRes:
    properties:
      data:
        $ref: '#/definitions/response.CustomerData'
      message:
        example: success message
        type: string
      success:
        example: true
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: my.full.name.in.lower.case@gmail.com
    name: Rezoan Tamal
  description: This is auth REST api server
  termsOfService: tbd
  title: auth
  version: "1.0"
paths: {}
swagger: "2.0"
